spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poloit_db
    username: polo_user
    password: secreta
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
